# postgres:
#   dsn: ""
#   host: "anchor-prod-eastel-bss-db.cj6m4oq2u9nh.ap-southeast-5.rds.amazonaws.com"
#   port: 5432
#   database: "anchor_iot"
#   user: "anchor_readonly"
#   password: "Ac123@%"
#   sslmode: "prefer"

postgres:
  dsn: ""
  host: "localhost"
  port: 5432
  database: "mydb"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"


mongo:
  uri: "mongodb+srv://prodUser:CxNFHCraErGeEsYI@easteldataanalysis.zwi2ei.mongodb.net/?appName=EastelDataAnalysis"
  #uri: "mongodb+srv://mongoAdmin:mongoAdmin@cluster0.awzu7vd.mongodb.net/"
  #uri: "mongodb+srv://user:password@cluster.mongodb.net/"
  eastel_database: "eastel-data"
  eastel_usage_collection: "usage_logs"
  eastel_usage_state_collection: "usage_log_sync_state"
  eastel_request_collection: "request_logs"
  eastel_request_state_collection: "request_log_sync_state"

sync:
  postgres_usage_source_table: "iot_portal_tb_usage_log"
  postgres_request_source_table: "iot_portal_tb_request_log"
  batch_size: 1000
  continuous: true
  poll_interval_seconds: 60
  lock_timeout_seconds: 3600
