postgres:
  dsn: ""
  host: "localhost"
  port: 5432
  database: "anchor_iot"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"

report_generation:
  source_queries_file: "quries.sql"
  split_queries_dir: "generated-queries"
  template_csv: "report-template.csv"
  output_csv: "report-output.csv"
  query_column_name: "Query"

variables:
  start_date: "2026-05-11"
  end_date: "2026-05-12"
